export const SET_CORREO_AUTENTICACION = 'SET_CORREO_AUTENTICACION';
export const SET_CONTRASEÑA_AUTENTICACION = 'SET_CONTRASEÑA_AUTENTICACION';
export const SET_TOKEN_AUTENTICACION = 'SET_TOKEN_AUTENTICACION';
export const SET_TOKENTEMP_AUTENTICACION = 'SET_TOKENTEMP_AUTENTICACION';
export const SET_NOMBRE_AUTENTICACION = 'SET_NOMBRE_AUTENTICACION';
